name: update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 1,3,5"   # every 30 mins

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@main
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: 💿 Install Jinja2 & requests                           
        run: pip install Jinja2 requests
      - name: 🍳 Update the README
        run: |
          cd ${GITHUB_WORKSPACE}/profile/src/
          python update.py
          cp ${GITHUB_WORKSPACE}/profile/README.md ${GITHUB_WORKSPACE}/README.md
      - name: 🚀 Deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
      - name: Delete History
        run: |
            # Checkout to a temporary branch
            git checkout --orphan temp_branch
            # Add all files and commit them
            git add -A
            git commit -am "feat(auto generate): Updated content"
            # Delete the main branch
            git branch -D main
            # Rename the temporary branch to main
            git branch -m main
            # Force update the repository
            git push -f origin main
